### PR TITLE
Support llama_encode (WIP)

### PR DESCRIPTION
**Pull request by ngxson**
```ts
await wllama.loadModelFromUrl("https://huggingface.co/Felladrin/gguf-flan-t5-large/resolve/main/flan-t5-large.Q2_K.gguf", {
  n_ctx: 1024,
});

output = await wllama.createCompletion("translate English to French: How old are you?", {
  nPredict: 20,
  sampling: { temp: 0 },
});

// output:  Les âges de vous êtes-vous?
// expected: Vous avez quel âge ?
```

### CODE REVIEW

**Comment by ngxson** [comment]
Quantized model is not usable (seems like flan requires a lot of precision)

FP16 (answer is more correct, but not the way french people usually say):

image

INT8 (answer is wrong):

image

**Comment by ngxson** [comment]
@felladrin I still can't get reliable results, but seems like problem comes from llama.cpp and not wllama.

This PR will be merged now.

**Comment by felladrin** [comment]
Thank you for implementing it, @ngxson!
I tested it with https://huggingface.co/Felladrin/gguf-MaxMini-Instruct-248M and it worked great!
Inference was considerably slower than a 248M decoder-only, but encoder-decoder models still have their uses!

**Comment by ngxson** [comment]
@felladrin Thanks for the info. I'm not sure why it's significant slower, probably something to be optimized from upstream.

And yeah I agree that encoder-decoder models are still useful. Personally I found that for more deterministic tasks like translating languages, it hallucinates less than decoder-only.

**Pull request merged**
