### PR TITLE
Force use of the cache if there is no internet connection

### PR DESCRIPTION
**Pull request by flatsiedatsie**
See:
https://github.com/ngxson/wllama/issues/87

Probably not the best solution, but it works.

It checks if `window.internet` is true of false. In my case a service worker sets window.internet to false if there is no internet connection.

I could also let the service worker cache the files, but then they'd be cached twice, right?

Another option would be to store the real size of the chunks in localstorage when a download starts, and then check if the cached file is the correct size based on that local information.

### CODE REVIEW

**Comment by ngxson** [comment]
Thanks for the suggestion. In fact, I intentionally force `GGUFRemoteBlob` to check online file (even if it's cached), because the file may changed. Disabling this will cause 2 problems:
- Half-downloaded file will never be detected (i.e. user downloading the file, but then reload the page mid-way)
- If upstream file is changed, cached file will still be used

IMO better way is to hide `enableOffline` inside an option an keep it disabled by default. The default behavior should not be changed (we always check online to see if the file changed or not)

**Comment by flatsiedatsie** [comment]
I don't disagree with the reasons to check for changes offline. But if there is no online to check, then falling back to whatever is available seems reasonable? If the process then fails, then the user can be recommended to connect to the internet to fix the issue.

It's a bit of a shame to have the model there, in the cache, but not being able to use it because it _might_ be broken?

> Half-downloaded file will never be detected

Indeed. Hence my vague idea to temporarily store the real size of the chunks in localstorage when a download starts. Then it's not necessary to go online to get the intended chunk sizes.

> If upstream file is changed, cached file will still be used

Is that bad? You could also argue it's a good thing to keep using the cached file, as it's the one that matches the cached version of Wllama in the service worker. Switching to a new AI model because something changed on Huggingface might lead to untested situations where the old version of Wllama cannot handle the updated model properly. Or it could even be that a good model was replaced by a malicious one.

> Disabling this will cause 2 problems

Yes, absolutely. But it also creates a feature, one that, IMHO, is quite important. The benefit of caching the files is not just faster loading, but also that you can download the AI models, then go to a remote location without internet (e.g. going to the park, going on a train or airplane, etc) and continue working.

I have also found that this is a good way to gain user trust. You can suggest to them to try out the alleged privacy protection by disabling wifi, and then verifying that the AI remains available.


> IMO better way is to hide enableOffline inside an option an keep it disabled by default.

Fine by me. Since I know when there is an internet connection or not, I can use that information when loading a new model.

I can attempt to create a PR, if you can help me a bit with getting the typescript wizardry fixed?

**Comment by flatsiedatsie** [comment]
Awesome! Thank you!

> Your browser may cache many web assets, but that does not mean the website can be used offline

True, but in my case I'm using a service worker, so everything is already designed to fully work when offline. Wllama was the only component that didn't gel with that setup yet.

**Comment by flatsiedatsie** [comment]
I just realized that the name of this issue might have been a bit unfortunate. The patch did not change the default behaviour of checking online. It only did so if a variable called `window.internet` existed, and was false. In all other cases it would still check online first.

**Comment by ngxson** [comment]
I'll replace this PR with #90

**Pull request closed without merging**
