### PR TITLE
add Blob support + OPFS + load from local file(s)

### LINKED ISSUE #42: [Idea] Load model from File Blob
With the introduction of heapfs, we can now do more low-level things.

The idea is to load File Blob directly into wllama's heap without creating any intermediate buffer.

This will ultimately allow us to use OPFS as mentioned in #38

### LINKED ISSUE #43: [Idea] Stream data from main thread to worker
~~Data is now passing as `Uint8Array`. We can do better by using Streams: https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams~~

We are now using `Blob` which already provides a `ReadableStream`.

### PR DESCRIPTION
**Pull request by ngxson**
Resolves #42 Resolves #43

- `loadModel()` now also accepts `Blob` or `File`
- added `GGUFRemoteBlob` that can stream Blob from a remote URL
- added example for loading local gguf files
- implement OPFS for cache

### CODE REVIEW

**Comment by flatsiedatsie** [comment]
Super cool.

I'm curious: how does this deal with memory/chunking? Can I feed it a files list for example? Or is this for single .gguf files only?

**Comment by ngxson** [comment]
@flatsiedatsie Yes, this is made so that we can feed in a list of gguf shards. Even better, this should allow us to load a big file from local hard drive without splitting it into shards.

`Blob` in js works a bit like file descriptor in low-level languages. It allows the program to read the file chunk by chunk (so it uses less RAM)

In theory, we could do the same with a remote file (i.e. `loadModelFromUrl`), but that requires some major changes will be quite messy. For now, let's just focus on loading a local file.

**Comment by felladrin** [comment]
> read the file chunk by chunk (so it uses less RAM)
> 
> In theory, we could do the same with a remote file (i.e. loadModelFromUrl)

Would love to see it in Wllama!
That's exactly how the loading of GGUF files was implemented in https://github.com/huggingface/ratchet

**Comment by flatsiedatsie** [comment]
> In theory, we could do the same with a remote file

That would be so great though!

**Comment by ngxson** [comment]
> Then people could create and share links that would instantly let them try .gguf files + prompts. HuggingFace could even integrate such a feature into their website. "Just one click to try the model on your own device, privacy protected". Though they would probably prefer to use Transformers.js. But you get my drift.

Great idea. I'm imagining an extension from that: An UI that you can select from a dropdown a list of prompts, maybe the list can be saved inside a config file in HF's repo. Probably this will be interesting for @julien-c

**Comment by ngxson** [comment]
@felladrin @flatsiedatsie Small update on this PR (and globally on the project): I recently have quite a lot of things to do in my life, so the progress is currently slow down a bit. But luckily, this PR is making some substantial progress. The only thing missing is support for OPFS cache on Safari due to [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=231706)

And a bit spoiler, I'm leaving cybersecurity and reorient myself to focus on machine learning. By september, when I move to the new job, I'll have more time dedicated to this project.

**Comment by flatsiedatsie** [comment]
It's all good! Wllama is now in a very useable anyway. It's a core pillar of the project I will release this month.

Good luck on the switch! You definitely have the skills for it :-)

**Comment by felladrin** [comment]
That's great news!! You've done a lot and Wllama is in great shape! Take your time and all the best with the career move!

**Comment by ngxson** [comment]
Good news everyone! This PR is now ready for testing. I've been able to add a small demo under `examples/basic` that allow user to pick a local gguf file (or multiple files)

image

It is however, quite annoying to me because we still can't load files bigger than 2GB, due to [ftell/fseek being limited to MAX_LONG](https://github.com/emscripten-core/emscripten/blob/main/system/lib/libc/musl/src/stdio/ftell.c), which is 2³¹ bytes. Basically this is even worst than the old day FAT32 since biggest file FAT32 can handle is 4GB (which is equivalent to MAX_UNSIGNED_LONG).

That aside, I'll merge this PR in the next days, so feel free to test it out. Thank you!

**Comment by felladrin** [comment]
Just tested it! And it's working fine, except for one thing:

It's not caching the models anymore on iOS browsers (tested with Mobile Safari and Mobile Brave)

On both, I'm getting the message `NOT using cache for (...)`.
image

So every time the page is refreshed, the model is fully downloaded again.

Notes:
- On iOS, the inference is running fine, after the model is downloaded. The problem is just that it's not being cached.
- On desktop browsers, everything is working fine.

**Comment by ngxson** [comment]
@felladrin I updated a small fix for Safari iOS. It kinda work for me, but a bit unstable (as usual, I think)

I didn't test with model bigger than 60MB, so please give git a try. Thank you!

**Comment by felladrin** [comment]
Let me check it now!

**Comment by felladrin** [comment]
Excellent 🙌 On iOS, it's now loading from the cache correctly!

image

**Pull request merged**
