### PR TITLE
Add delete method to cacheManager

### PR DESCRIPTION
**Pull request by flatsiedatsie**
Allows for the deletion of a specific LLM from the cache, based on a partial file name.

### CODE REVIEW

**Comment by felladrin** [comment]
Good addition!

Any thoughts on a way to delete all the cache files, in case we want/need to debug something / free up space?
(Maybe "if the hint is undefined, it deletes all files from cache"?)

**Comment by ngxson** [comment]
I'd suggest a function that accepts function as input (a bit like `array.filter`)

```ts
  /**
   * Delete files from the cache
   */
  async delete(predicate: (entry: CacheEntry) => boolean): Promise<void> {
    const cacheDir = await getCacheDir();
    const list = await CacheManager.list();
    for (const item of list) {
      if (predicate(item)) {
        cacheDir.removeEntry(item.name);
      }
    }
  },
```

**Comment by flatsiedatsie** [comment]
I've changed it to the suggested code, thank you. 

How would I use it with a function? I'm guessing something like this?

```
await window.llama_cpp_app.cacheManager.delete((cache_item) => {
  if(typeof cache_item.name == 'string' && cache_item.name.indexOf(partial_url) != -1){
    return true
  }
  else{
    return false
  }
});
```

**Comment by ngxson** [comment]
On second though, I think having a function like this will make more sense:

```ts
await CacheManager.delete("https://huggingface.co/.../my_model.gguf");

// or
const items = await CacheManager.list();
await CacheManager.delete(items[0].name);
```

I'm replacing this PR with https://github.com/ngxson/wllama/pull/80 , is that OK for you @flatsiedatsie ?

**Comment by flatsiedatsie** [comment]
Of course, all fine!

**Pull request closed without merging**
